      - name: IPTV Temizlik Kodunu Çalıştır
        run: |
          python update_list.py
          ls -la  # Bu komut dosya orada mı değil mi loglarda gösterir

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          if [ -f "tr.m3u" ]; then
            git add tr.m3u
            git commit -m "IPTV Güncellendi" || echo "Commitlenecek değişiklik yok."
            git push
          else
            echo "UYARI: Dosya bulunamadı, script dosyayı oluşturamamış olabilir."
            exit 0 # Süreci hata vermeden bitir
          fi
